spring:
  kafka:
    consumer:
      auto-offset-reset: earliest

resilience4j:
  circuitbreaker:
    instances:
      externalProvider:

        slidingWindowSize: 5
        failureRateThreshold: 50

